//Detect Azure AD PIM activiations
AuditLogs
// extend LocalTime to your time zone
| extend LocalTime=TimeGenerated - 4h
| where LocalTime > ago(30d)
| where OperationName == 'Add member to role completed (PIM activation)'
| extend User = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| extend ['Azure AD Role Name'] = tostring(TargetResources[0].displayName)
| project LocalTime, User, ['Azure AD Role Name'], ['Activation Reason']=ResultReason
